### PR TITLE
Use Self where possible

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by pintariching** [comment]
Is there any benefit to using `Self` instead of the struct name? Or is it just a matter of convention?

Also the same question for `vec![]` vs `Vec::new()`.

**Comment by adamnemecek** [comment]
It's more idiomatic. Also you already use Self:: instead of the struct name in several places so this unifies it.

**Comment by pintariching** [comment]
The changes seem to make the build fail. Can you check it out?

**Comment by adamnemecek** [comment]
Done.

**Pull request merged**
